## Generate Text
POST http://localhost:3000/api/generateText HTTP/1.1
content-type: application/json

{
   "prompt": "Greet the user with a friendly message."
}
###

## Generate Recipe
POST http://localhost:3000/api/generateRecipe HTTP/1.1
content-type: application/json

{
   "prompt": "Cherry pie"
}
###